/**
 * The icons this app actually uses, re-exported by name.
 *
 * `Icon.svelte` resolves names against this registry instead of importing
 * `@hugeicons/core-free-icons` wholesale — the package ships ~13,500 icons and
 * bundles to ~5.5 MB, while this list tree-shakes down to a few kilobytes.
 * Using a new icon means adding one line here; in dev, `Icon` warns about
 * names that are missing.
 */
export {
	Alert01Icon,
	Analytics01Icon,
	ArrowDown01Icon,
	ArrowDownRight01Icon,
	ArrowLeft01Icon,
	ArrowRight01Icon,
	ArrowUp01Icon,
	ArrowUpRight01Icon,
	Bookmark01Icon,
	Building01Icon,
	Calendar01Icon,
	Camera01Icon,
	Cancel01Icon,
	ChartLineData01Icon,
	CheckmarkCircle01Icon,
	Clock01Icon,
	ComputerIcon,
	Copy01Icon,
	CreditCardIcon,
	DashboardSquare01Icon,
	Delete02Icon,
	Download01Icon,
	Edit01Icon,
	FavouriteIcon,
	FilterRemoveIcon,
	GithubIcon,
	GoogleIcon,
	Home01Icon,
	Image01Icon,
	InboxIcon,
	InformationCircleIcon,
	Invoice01Icon,
	Key01Icon,
	Layers01Icon,
	Legal01Icon,
	Logout01Icon,
	Mail01Icon,
	Menu01Icon,
	Moon02Icon,
	MoreVerticalIcon,
	Notification01Icon,
	PlayIcon,
	PlusSignIcon,
	RocketIcon,
	Search01Icon,
	Settings01Icon,
	Share01Icon,
	Shield01Icon,
	SidebarLeft01Icon,
	SmartPhone01Icon,
	SquareLock01Icon,
	StarIcon,
	Sun01Icon,
	Task01Icon,
	Tick02Icon,
	User02Icon,
	UserAdd01Icon,
	UserGroupIcon,
	UserRemove01Icon,
	ViewIcon,
	ViewOffSlashIcon,
	Wallet01Icon
} from '@hugeicons/core-free-icons';
